name: Build Typst
on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Compile
        uses: typst-community/setup-typst@v4
      - run: typst compile main.typ Luca_Parolini.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Luca_Parolini
          path: Luca_Parolini.pdf

      - name: Release PDF
        uses: softprops/action-gh-release@v2
        # if: github.ref_type == 'tag'
        with:
          tag_name: latest
          name: Latest build
          files: Luca_Parolini
          make_latest: true
